/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomatizacionesRouteImport } from './routes/automatizaciones'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as ClosersRouteImport } from './routes/closers'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ConversacionesRouteImport } from './routes/conversaciones'
import { Route as IaRouteImport } from './routes/ia'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ReportesRouteImport } from './routes/reportes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatizacionesRoute = AutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosersRoute = ClosersRouteImport.update({
  id: '/closers',
  path: '/closers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversacionesRoute = ConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automatizaciones': typeof AutomatizacionesRoute
  '/chatbot': typeof ChatbotRoute
  '/closers': typeof ClosersRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contactos': typeof ContactosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/ia': typeof IaRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pedidos': typeof PedidosRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automatizaciones': typeof AutomatizacionesRoute
  '/chatbot': typeof ChatbotRoute
  '/closers': typeof ClosersRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contactos': typeof ContactosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/ia': typeof IaRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pedidos': typeof PedidosRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automatizaciones': typeof AutomatizacionesRoute
  '/chatbot': typeof ChatbotRoute
  '/closers': typeof ClosersRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contactos': typeof ContactosRoute
  '/conversaciones': typeof ConversacionesRoute
  '/ia': typeof IaRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pedidos': typeof PedidosRoute
  '/productos': typeof ProductosRoute
  '/reportes': typeof ReportesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automatizaciones'
    | '/chatbot'
    | '/closers'
    | '/configuracion'
    | '/contactos'
    | '/conversaciones'
    | '/ia'
    | '/leads'
    | '/login'
    | '/oportunidades'
    | '/pedidos'
    | '/productos'
    | '/reportes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automatizaciones'
    | '/chatbot'
    | '/closers'
    | '/configuracion'
    | '/contactos'
    | '/conversaciones'
    | '/ia'
    | '/leads'
    | '/login'
    | '/oportunidades'
    | '/pedidos'
    | '/productos'
    | '/reportes'
  id:
    | '__root__'
    | '/'
    | '/automatizaciones'
    | '/chatbot'
    | '/closers'
    | '/configuracion'
    | '/contactos'
    | '/conversaciones'
    | '/ia'
    | '/leads'
    | '/login'
    | '/oportunidades'
    | '/pedidos'
    | '/productos'
    | '/reportes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomatizacionesRoute: typeof AutomatizacionesRoute
  ChatbotRoute: typeof ChatbotRoute
  ClosersRoute: typeof ClosersRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ContactosRoute: typeof ContactosRoute
  ConversacionesRoute: typeof ConversacionesRoute
  IaRoute: typeof IaRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PedidosRoute: typeof PedidosRoute
  ProductosRoute: typeof ProductosRoute
  ReportesRoute: typeof ReportesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatizaciones': {
      id: '/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AutomatizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closers': {
      id: '/closers'
      path: '/closers'
      fullPath: '/closers'
      preLoaderRoute: typeof ClosersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversaciones': {
      id: '/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof ConversacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomatizacionesRoute: AutomatizacionesRoute,
  ChatbotRoute: ChatbotRoute,
  ClosersRoute: ClosersRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ContactosRoute: ContactosRoute,
  ConversacionesRoute: ConversacionesRoute,
  IaRoute: IaRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OportunidadesRoute: OportunidadesRoute,
  PedidosRoute: PedidosRoute,
  ProductosRoute: ProductosRoute,
  ReportesRoute: ReportesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
